# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/OLED_constraints.xdc

# Block Designs: bd/OLED_LED_BUTTON_design/OLED_LED_BUTTON_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLED_LED_BUTTON_design || ORIG_REF_NAME==OLED_LED_BUTTON_design} -quiet] -quiet

# IP: bd/OLED_LED_BUTTON_design/ip/OLED_LED_BUTTON_design_processing_system7_0_0/OLED_LED_BUTTON_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLED_LED_BUTTON_design_processing_system7_0_0 || ORIG_REF_NAME==OLED_LED_BUTTON_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/OLED_LED_BUTTON_design/ip/OLED_LED_BUTTON_design_ZedboardOLED_0_0/OLED_LED_BUTTON_design_ZedboardOLED_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLED_LED_BUTTON_design_ZedboardOLED_0_0 || ORIG_REF_NAME==OLED_LED_BUTTON_design_ZedboardOLED_0_0} -quiet] -quiet

# IP: bd/OLED_LED_BUTTON_design/ip/OLED_LED_BUTTON_design_axi_gpio_0_0/OLED_LED_BUTTON_design_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLED_LED_BUTTON_design_axi_gpio_0_0 || ORIG_REF_NAME==OLED_LED_BUTTON_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/OLED_LED_BUTTON_design/ip/OLED_LED_BUTTON_design_axi_gpio_1_0/OLED_LED_BUTTON_design_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLED_LED_BUTTON_design_axi_gpio_1_0 || ORIG_REF_NAME==OLED_LED_BUTTON_design_axi_gpio_1_0} -quiet] -quiet

# IP: bd/OLED_LED_BUTTON_design/ip/OLED_LED_BUTTON_design_xbar_0/OLED_LED_BUTTON_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLED_LED_BUTTON_design_xbar_0 || ORIG_REF_NAME==OLED_LED_BUTTON_design_xbar_0} -quiet] -quiet

# IP: bd/OLED_LED_BUTTON_design/ip/OLED_LED_BUTTON_design_ps7_0_axi_periph_0/OLED_LED_BUTTON_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLED_LED_BUTTON_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==OLED_LED_BUTTON_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/OLED_LED_BUTTON_design/ip/OLED_LED_BUTTON_design_rst_ps7_0_100M_0/OLED_LED_BUTTON_design_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLED_LED_BUTTON_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==OLED_LED_BUTTON_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/OLED_LED_BUTTON_design/ip/OLED_LED_BUTTON_design_auto_pc_0/OLED_LED_BUTTON_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OLED_LED_BUTTON_design_auto_pc_0 || ORIG_REF_NAME==OLED_LED_BUTTON_design_auto_pc_0} -quiet] -quiet

# XDC: bd/OLED_LED_BUTTON_design/OLED_LED_BUTTON_design_ooc.xdc
