# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/justin/vivado_projects/OLED_LED_BUTTON/OLED_LED_BUTTON.srcs/sources_1/bd/OLED_LED_BUTTON_design/ip/OLED_LED_BUTTON_design_xbar_0/OLED_LED_BUTTON_design_xbar_0.xci
# IP: The module: 'OLED_LED_BUTTON_design_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/justin/vivado_projects/OLED_LED_BUTTON/OLED_LED_BUTTON.srcs/sources_1/bd/OLED_LED_BUTTON_design/ip/OLED_LED_BUTTON_design_xbar_0/OLED_LED_BUTTON_design_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'OLED_LED_BUTTON_design_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/justin/vivado_projects/OLED_LED_BUTTON/OLED_LED_BUTTON.srcs/sources_1/bd/OLED_LED_BUTTON_design/ip/OLED_LED_BUTTON_design_xbar_0/OLED_LED_BUTTON_design_xbar_0.xci
# IP: The module: 'OLED_LED_BUTTON_design_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/justin/vivado_projects/OLED_LED_BUTTON/OLED_LED_BUTTON.srcs/sources_1/bd/OLED_LED_BUTTON_design/ip/OLED_LED_BUTTON_design_xbar_0/OLED_LED_BUTTON_design_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'OLED_LED_BUTTON_design_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
