# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/justin/vivado_projects/OLED_LED_BUTTON/OLED_LED_BUTTON.srcs/sources_1/bd/OLED_LED_BUTTON_design/ip/OLED_LED_BUTTON_design_ZedboardOLED_0_0/OLED_LED_BUTTON_design_ZedboardOLED_0_0.xci
# IP: The module: 'OLED_LED_BUTTON_design_ZedboardOLED_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/justin/vivado_projects/OLED_LED_BUTTON/OLED_LED_BUTTON.srcs/sources_1/bd/OLED_LED_BUTTON_design/ip/OLED_LED_BUTTON_design_ZedboardOLED_0_0/src/charLib/charLib.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==charLib || ORIG_REF_NAME==charLib} -quiet] -quiet

# XDC: /home/justin/vivado_projects/OLED_LED_BUTTON/OLED_LED_BUTTON.srcs/sources_1/bd/OLED_LED_BUTTON_design/ip/OLED_LED_BUTTON_design_ZedboardOLED_0_0/src/charLib/charLib_ooc.xdc

# IP: /home/justin/vivado_projects/OLED_LED_BUTTON/OLED_LED_BUTTON.srcs/sources_1/bd/OLED_LED_BUTTON_design/ip/OLED_LED_BUTTON_design_ZedboardOLED_0_0/OLED_LED_BUTTON_design_ZedboardOLED_0_0.xci
# IP: The module: 'OLED_LED_BUTTON_design_ZedboardOLED_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/justin/vivado_projects/OLED_LED_BUTTON/OLED_LED_BUTTON.srcs/sources_1/bd/OLED_LED_BUTTON_design/ip/OLED_LED_BUTTON_design_ZedboardOLED_0_0/src/charLib/charLib.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==charLib || ORIG_REF_NAME==charLib} -quiet] -quiet

# XDC: /home/justin/vivado_projects/OLED_LED_BUTTON/OLED_LED_BUTTON.srcs/sources_1/bd/OLED_LED_BUTTON_design/ip/OLED_LED_BUTTON_design_ZedboardOLED_0_0/src/charLib/charLib_ooc.xdc
